--- 

  - name: Include RPM package specific variables
    include_vars: "rpm_family.yml"
    when: ansible_os_family == "RedHat"

  - name: Install the epl packages
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Install Redhat redis server
    yum: name={{ item }} state=present
    with_items: "{{ redhat_pkg }}"
    when: ansible_os_family == "RedHat"

  - name: Copy Customized redis.conf file
    template: src=redis.conf dest={{ conf_path }}
    notify:
      - Restart Redis Server

  - name: Set the OverCommit value
    sysctl: name=vm.overcommit_memory value={{ redis_overcommit_memory }} state=present

  - name: Start the Redis service
    service: name={{ redis_service_name }} state=started enabled=yes
